#!/bin/bash
# BEGIN_ICS_COPYRIGHT8 ****************************************
#
# Copyright (c) 2015-2020, Intel Corporation
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
#
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
# END_ICS_COPYRIGHT8   ****************************************

# [ICS VERSION STRING: unknown]

# select an HPL.dat file and copy to all hosts
#   MPI_HOSTS  - mpi_hosts file to use (default is $PWD/mpi_hosts)

MPI_HOSTS=${MPI_HOSTS:-$PWD/mpi_hosts}

if [ $(echo $MPI_HOSTS|cut -c1) != '/' ]
then
	MPI_HOSTS="$PWD/$MPI_HOSTS"
fi

arch=ICS.`uname -s`.`./get_mpi_cc.sh`

TEMP_FILE="$(mktemp)"
trap "rm -rf $TEMP_FILE; exit 1" SIGINT SIGHUP SIGTERM
trap "rm -rf $TEMP_FILE" EXIT

Usage()
{
	echo " Usage: ./config_hpl2 [-l] config_name [problem_size]"
	echo "     -l - only configure local file, default is to configure on all mpi_hosts"
	echo " For example: ./config_hpl2 32t"
	echo " either create hpl-config/HPL.dat-'config_name'"
	echo " or select one of:"
	cd hpl-config; ls HPL.dat-*[!~]
	exit 2
}

lopt=n
while getopts l param
do
	case $param in
	l)	lopt="y";;
	*)	Usage;;
	esac
done
shift $((OPTIND-1))

if [ -z "$1" ]
then 
	Usage
else
	config_name=$1
fi
if [ $lopt = n -a ! -f $MPI_HOSTS ]
then
	echo " Please create $MPI_HOSTS file with the list of "
	echo " hosts in this cluster. One hostname per line."
	echo " See mpi_hosts.sample file"
	exit 1
fi

if [ ! -d hpl-2.3/bin/$arch ]
then
	echo " Could not find hpl2 compiled for $arch."
	echo " Please compile hpl2 using:"
	echo " make XHPL2"
	exit 1
fi
if [ ! -f hpl-config/HPL.dat-$config_name ]
then
	echo " HPL.dat file for $config_name is not available"
	echo " either create hpl-config/HPL.dat-$config_name"
	echo " or select one of:"
	cd hpl-config; ls HPL.dat-*[!~]
	exit 1
fi

file=hpl-config/HPL.dat-$config_name
if [ ! -z "$2" ]
then
	# change line 6 to requested problem size
	sed -e "6s/^[0-9]*/$2/" < $file > $TEMP_FILE
	if [ $lopt = n ]
	then
		opascpall -p -h "`sort -u $MPI_HOSTS`" $TEMP_FILE $PWD/hpl-2.3/bin/$arch/HPL.dat
	else
		# avoid any cp alias
		/bin/cp -f $TEMP_FILE $PWD/hpl-2.3/bin/$arch/HPL.dat
	fi
else
	if [ $lopt = n ]
	then
		opascpall -p -h "`sort -u $MPI_HOSTS`" $file $PWD/hpl-2.3/bin/$arch/HPL.dat
	else
		# avoid any cp alias
		/bin/cp -f $file $PWD/hpl-2.3/bin/$arch/HPL.dat
	fi
fi
