#!/bin/sh
# BEGIN_ICS_COPYRIGHT8 ****************************************
# 
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# END_ICS_COPYRIGHT8   ****************************************

# [ICS VERSION STRING: unknown]

# Perform a simple benchmark of MPI over a set of nodes

# BASE PATH TO MPI EXECUTABLES: To use an alternate location,
# either edit this line or set MPICH_PREFIX in your environment.
# see select_mpi for the set of default MPI selections
# default to MPI used for build
#   MPI_HOSTS  - mpi_hosts file to use (default is $PWD/mpi_hosts)
MPICH_PREFIX=${MPICH_PREFIX:-`cat .prefix 2>/dev/null`}

MPI_HOSTS=${MPI_HOSTS:-$PWD/mpi_hosts}

if [ $(echo $MPI_HOSTS|cut -c1) != '/' ]
then
	MPI_HOSTS="$PWD/$MPI_HOSTS"
fi

trap "exit 1" SIGHUP SIGTERM SIGINT

if [ -z "$1" ]
then 
	echo " Usage: run_bench number_processes [max_size] [expanded]"
	echo " For example: ./run_bench 2"
	exit 1
else
	NUM_PROCESSES=$1
fi
if [ -z $2 ]
then 
	MAX_SIZE=4194304
	echo " Setting the default Maximum Message Size to $MAX_SIZE"
else
	MAX_SIZE=$2
fi
if [ ! -z $3 ]
then
	expanded=y
else
	expanded=n
fi

PARAM_FILE=
APP=bench
LOGFILE=
. ./prepare_run

PARAM_FILE_BASIC="$PWD/mpi.param.pallas"
MPI_RUN_CMD="$MPI_RUN_CMD ${PARAM_ARG:+$PARAM_ARG $PARAM_FILE_BASIC} "
LATENCY_CMD="latency/latency"
BANDWIDTH_CMD="bandwidth/bw"
PMB_CMD="PMB2.2.1/SRC_PMB/PMB-MPI1"

PARAM_FILE_HPL="$PWD/mpi.param.hpl"
MPI_RUN_CMD_HPL="$MPI_RUN_CMD ${PARAM_ARG:+$PARAM_ARG $PARAM_FILE_HPL} "
HPL_DIR="hpl/bin/ICS.`uname -s`.`./get_mpi_cc.sh`"
HPL_CMD="./xhpl"

if [ "$expanded" = "n" ]
then
	set ""
else
	if [ $MPD_MODE != 0 ]
	then
		echo "Expanded mode only supported for MPICH1 in mpirun mode"
		exit 1
	fi
	MPI_RUN_CMD="$MPICH_PREFIX/bin/mpirun_rsh -np $NUM_PROCESSES -hostfile $MPI_HOSTS ${PARAM_ARG:+$PARAM_ARG $PARAM_FILE_BASIC} "
	MPI_RUN_CMD_HPL="$MPICH_PREFIX/bin/mpirun_rsh -np $NUM_PROCESSES -hostfile $MPI_HOSTS ${PARAM_ARG:+$PARAM_ARG $PARAM_FILE_HPL} "
	set "VIADEV_SMP=1 VIADEV_NUM_RDMA_BUFFER=32" "VIADEV_SMP=1 VIADEV_NUM_RDMA_BUFFER=0" "VIADEV_SMP=0 VIADEV_NUM_RDMA_BUFFER=32" "VIADEV_SMP=0 VIADEV_NUM_RDMA_BUFFER=0" "VIADEV_SMP=0 VIADEV_NUM_RDMA_BUFFER=0 VIADEV_SPIN_COUNT=100"
fi

show_mpi_hosts | tee -a $LOGFILE
echo " Running Latency ..." | tee -a $LOGFILE
for parms in "$@"
do
	echo " Running Latency with $parms ..." | tee -a $LOGFILE
	echo " Using: $MPI_RUN_CMD -np 2 $parms $LATENCY_CMD LOOPS SIZE" >> $LOGFILE
	loops=10000
	size=0
	while [ "$size" -le "$MAX_SIZE" ]
	do
		echo " Running Latency for size $size"
		set -x
		$MPI_RUN_CMD -np 2 $parms $LATENCY_CMD $loops $size 2>&1|tee -i -a $LOGFILE
		set +x
		if [ $size -lt 8 ]
		then
			size=`expr $size + 1`
		elif [ $size -lt 2048 ]
		then
			loops=5000
    		size=`expr $size + $size`
		elif [ $size -lt 1000000 ]
		then
			loops=1000
    		size=`expr $size + $size`
		else
			loops=20
    		size=`expr $size + $size`
		fi
	done
	echo "########################################### " >> $LOGFILE
done
sleep 1
wait


echo " Running Bandwidth ..." | tee -a $LOGFILE
for parms in "$@"
do
	echo " Running Bandwidth with $parms ..." | tee -a $LOGFILE
	echo " Using: $MPI_RUN_CMD -np 2 $parms $BANDWIDTH_CMD LOOPS SIZE" >> $LOGFILE
	loops=100
	size=1024
	while [ "$size" -le "$MAX_SIZE" ]
	do
		echo " Running Bandwidth for size $size"
		set -x
		$MPI_RUN_CMD -np 2 $parms $BANDWIDTH_CMD $loops $size 2>&1|tee -i -a $LOGFILE
		set +x
    	size=`expr $size + $size`
	done
	echo "########################################### " >> $LOGFILE
done
sleep 5
wait


echo " Running High Performance Computing Linpack Benchmark (HPL) ..." | tee -a $LOGFILE
./config_hpl ${NUM_PROCESSES}s
for parms in "$@"
do
	(
		echo " Running HPL with $parms ..."
		set -x
		cd $HPL_DIR; $MPI_RUN_CMD_HPL $parms $HPL_CMD
		set +x
	) 2>&1 | tee -i -a $LOGFILE
	echo "########################################### " >> $LOGFILE
done
sleep 1
wait


echo " Running Pallas ..." | tee -a $LOGFILE
for parms in "$@"
do
	(
		echo " Running Pallas with $parms ..."
		set -x
		$MPI_RUN_CMD -np $NUM_PROCESSES $parms $PMB_CMD
		set +x
	) 2>&1 | tee -i -a $LOGFILE
	echo "########################################### " >> $LOGFILE
done
