#!/bin/sh
# BEGIN_ICS_COPYRIGHT8 ****************************************
# 
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# END_ICS_COPYRIGHT8   ****************************************

# [ICS VERSION STRING: unknown]

# BASE PATH TO MPI EXECUTABLES: To use an alternate location, 
# either edit this line or set MPICH_PREFIX in your environment.
# see select_mpi for the set of default MPI selections
# default to MPI used for build
MPICH_PREFIX=${MPICH_PREFIX:-`cat .prefix 2>/dev/null`}

trap "exit 1" SIGHUP SIGTERM SIGINT

if [ -z "$1" ]
then
	echo "Usage: run_mbw_mr3 number_processes [osu_mbw_mr arguments]]" >&2
	echo "number_processes may be 'all' in which case one rank will be started for" >&2
	echo "every process in the mpi_hosts file" >&2
	echo "This application requires an even number of processes" >&2
	echo  >&2
	echo "osu_mbw_mr arguments:" >&2
	echo "  -r=<0,1>         Print uni-directional message rate (default 1)" >&2
	echo "  -p=<pairs>       Number of pairs involved (default np / 2)" >&2
	echo "  -w=<window>      Number of messages sent before acknowledgement (64, 10)" >&2
	echo "                   [cannot be used with -v]" >&2
	echo "  -v               Vary the window size (default no)" >&2
	echo "                   [cannot be used with -w]" >&2
	echo "  -h               Print this help" >&2
	echo  >&2
	echo "  Note: This benchmark relies on block ordering of the ranks.  Please see" >&2
	echo "        the OSU benchmarks README for more information." >&2
	echo  >&2
	exit 2
else
	NUM_PROCESSES=$1
	shift
fi

MULT_PROCESSES=2

CMD="osu-micro-benchmarks-3.8-July12/mpi/pt2pt/osu_mbw_mr $@"

APP=osu_mbw_mr
LOGFILE=
. ./prepare_run

(
	echo " Running Multi-Bandwidth 3.8 ..."
	show_mpi_hosts
	set -x
	$MPI_RUN_CMD $CMD
	set +x
) 2>&1 | tee -i -a $LOGFILE
echo "########################################### " >> $LOGFILE
