#!/bin/sh
# BEGIN_ICS_COPYRIGHT8 ****************************************
# 
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# END_ICS_COPYRIGHT8   ****************************************

trap "exit 1" SIGHUP SIGTERM SIGINT

CURTIME=`date +%d%b%y%H%M%S`
if [ ! -d logs ]
then
	`mkdir logs`
fi
if [ -z $1 ]
then 
	echo " Setting the default Maximum Message Size to 4194304"
	MAX_SIZE=4194304
	mult=4
	size=4096
elif [ "$1" = full ]
then
	MAX_SIZE=4194304
	mult=2
	size=1024
else
	MAX_SIZE=$1
	mult=4
	size=4096
fi
LOGFILE=$PWD/logs/log.$CURTIME
echo " Running MPI tests with 2 processes"
echo " logfile $LOGFILE"
> $LOGFILE

#MPI_RUN_CMD="/opt/opa/bin/mpirun -np 2 -paramfile $PWD/mpi.param.pallas -hostfile mpi_hosts "
MPI_RUN_CMD="mpiexec -n 2 -env I_MPI_DEVICE rdma"
BANDWIDTH_CMD="bandwidth/bw 400"

echo " Running Bandwidth ..." | tee -a $LOGFILE
echo " Using: $MPI_RUN_CMD $BANDWIDTH_CMD SIZE" >> $LOGFILE
while [ "$size" -le "$MAX_SIZE" ]
do
	echo " Running Bandwith for size $size"
	set -x
	$MPI_RUN_CMD $BANDWIDTH_CMD $size 2>&1|tee -i -a $LOGFILE
	set +x
    size=`expr $size \* $mult`
done
echo "########################################### " >> $LOGFILE
