#!/bin/sh
# BEGIN_ICS_COPYRIGHT8 ****************************************
# 
# Copyright (c) 2015, Intel Corporation
# 
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# 
#     * Redistributions of source code must retain the above copyright notice,
#       this list of conditions and the following disclaimer.
#     * Redistributions in binary form must reproduce the above copyright
#       notice, this list of conditions and the following disclaimer in the
#       documentation and/or other materials provided with the distribution.
#     * Neither the name of Intel Corporation nor the names of its contributors
#       may be used to endorse or promote products derived from this software
#       without specific prior written permission.
# 
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
# 
# END_ICS_COPYRIGHT8   ****************************************

trap "exit 1" SIGHUP SIGTERM SIGINT

CURTIME=`date +%d%b%y%H%M%S`
NPB_DIR="NPB2.3/bin"
if [ ! -d logs ]
then
	`mkdir logs`
fi
if [ -z "$1"  -o -z "$2" ]
then 
	echo " Usage: run_npb number_processes class [test ...]"
	echo " For example: ./run_npb 2 A"
	exit 1
else
	NUM_PROCESSES=$1
	CLASS=$2
	shift
	shift
	TESTS="$*"
	if [ -z "$TESTS" ]
	then
		TESTS=`cd $NPB_DIR; ls *.$CLASS.$NUM_PROCESSES 2>/dev/null|cut -f1 -d.`
	fi
	if [ -z "$TESTS" ]
	then
		echo " No tests compiled for class $CLASS $NUM_PROCESSES processes"
		echo " The following tests have been compiled:"
		( cd $NPB_DIR; ls *.[ABC].* )
		exit 1
	fi
fi
LOGFILE=$PWD/logs/log.$CURTIME
echo " Running MPI tests with $NUM_PROCESSES processes"
echo " logfile $LOGFILE"
> $LOGFILE

#MPI_RUN_CMD="/opt/opa/bin/mpirun -np $NUM_PROCESSES -paramfile $PWD/mpi.param.hpl -hostfile $PWD/mpi_hosts "
MPI_RUN_CMD="mpiexec -n $NUM_PROCESSES -env I_MPI_DEVICE rdma"

echo " Running NASA Parallel Benchmark (NPB) ..." | tee -a $LOGFILE
for test in $TESTS
do
	echo "########################################### " >> $LOGFILE
	echo "Running $test.$CLASS.$NUM_PROCESSES..." | tee -a $LOGFILE
	if [ ! -f $NPB_DIR/$test.$CLASS.$NUM_PROCESSES ]
	then
		echo "$test.$CLASS.$NUM_PROCESSES: Not found, skipping" | tee -a $LOGFILE
	else
		(
			set -x
			$MPI_RUN_CMD $NPB_DIR/$test.$CLASS.$NUM_PROCESSES
			set +x
		) 2>&1 | tee -i -a $LOGFILE
	fi
done
echo "########################################### " >> $LOGFILE
